from __future__ import annotations

import shlex
from dataclasses import dataclass
from pathlib import Path

from dflasher.model_profile import LayerPolicy, resolve_model_profile, target_layer_ids_for_policy


@dataclass(frozen=True)
class SpeculatorsRecipe:
    source_model: str
    output_dir: Path
    data: str = "sharegpt"
    max_samples: int = 5000
    seq_length: int = 8192
    epochs: int = 5
    learning_rate: float = 3e-4
    block_size: int = 8
    max_anchors: int = 3072
    num_layers: int = 5
    draft_vocab_size: int = 8192
    vllm_port: int = 8000
    train_gpus: str = "0"
    vllm_gpus: str = "0"
    target_layer_ids: tuple[int, ...] | None = None
    layer_policy: LayerPolicy = "auto"
    trust_remote_code: bool = False
    vllm_args: tuple[str, ...] = ()
    prepare_args: tuple[str, ...] = ()


def default_target_layer_ids(
    source_model: str,
    num_layers: int = 3,
    layer_policy: LayerPolicy = "speculators",
    trust_remote_code: bool = False,
) -> tuple[int, ...]:
    profile = resolve_model_profile(source_model, trust_remote_code=trust_remote_code)
    if layer_policy == "speculators" and num_layers != 3:
        return target_layer_ids_for_policy(
            profile.num_hidden_layers or 0,
            profile.family,
            "dflash5",
        )
    return target_layer_ids_for_policy(
        profile.num_hidden_layers or 0,
        profile.family,
        layer_policy,
    )


def render_speculators_script(recipe: SpeculatorsRecipe) -> str:
    target_layer_ids = recipe.target_layer_ids or default_target_layer_ids(
        recipe.source_model,
        3,
        recipe.layer_policy,
        recipe.trust_remote_code,
    )
    target_layers = " ".join(str(layer_id) for layer_id in target_layer_ids)
    q = shlex.quote
    output_dir = q(str(recipe.output_dir))
    hidden_states_dir = q(str(recipe.output_dir / "hidden_states"))
    checkpoint_dir = q(str(recipe.output_dir / "checkpoints"))
    source_model = q(recipe.source_model)
    data = q(recipe.data)
    vllm_args = " ".join(q(arg) for arg in recipe.vllm_args)
    prepare_args = " ".join(q(arg) for arg in recipe.prepare_args)

    return f"""#!/usr/bin/env bash
set -euo pipefail

# Generated by dflasher for vLLM Speculators DFlash training.
# Prerequisites:
#   uv pip install "speculators>=0.5.0"
#   uv pip install "vllm>=0.20.1"
#
# For serious training, use separate GPUs for vLLM hidden-state serving and training.

MODEL={source_model}
DATA={data}
OUTPUT_DIR={output_dir}
HIDDEN_STATES_DIR={hidden_states_dir}
LOG_DIR="$OUTPUT_DIR/logs"
VLLM_PORT={recipe.vllm_port}
TARGET_LAYER_IDS=({target_layers})
TRUST_REMOTE_CODE_ARG={"--trust-remote-code" if recipe.trust_remote_code else ""}
mkdir -p "$LOG_DIR"

echo "==> Preparing data"
python scripts/prepare_data.py \\
  --model "$MODEL" \\
  --data "$DATA" \\
  --output "$OUTPUT_DIR" \\
  --max-samples {recipe.max_samples} \\
  --seq-length {recipe.seq_length} \\
  $TRUST_REMOTE_CODE_ARG \\
  {prepare_args}

echo "==> Launching vLLM hidden-state server"
CUDA_VISIBLE_DEVICES={q(recipe.vllm_gpus)} python -m dflasher.hidden_server "$MODEL" \\
  --hidden-states-path "$HIDDEN_STATES_DIR" \\
  --target-layer-ids "${{TARGET_LAYER_IDS[@]}}" \\
  $TRUST_REMOTE_CODE_ARG \\
  -- --port "$VLLM_PORT" $TRUST_REMOTE_CODE_ARG {vllm_args} > "$LOG_DIR/hidden_server.log" 2>&1 &
VLLM_PID=$!

cleanup() {{
  kill "$VLLM_PID" 2>/dev/null || true
  wait "$VLLM_PID" 2>/dev/null || true
}}
trap cleanup EXIT

SECONDS_WAITED=0
until curl -sf "http://localhost:${{VLLM_PORT}}/health" >/dev/null 2>&1; do
  if ! kill -0 "$VLLM_PID" 2>/dev/null; then
    echo "Hidden-state server exited before becoming healthy." >&2
    tail -n 200 "$LOG_DIR/hidden_server.log" >&2 || true
    exit 1
  fi
  if [ "$SECONDS_WAITED" -ge 900 ]; then
    echo "Timed out waiting for hidden-state server health check." >&2
    tail -n 200 "$LOG_DIR/hidden_server.log" >&2 || true
    exit 1
  fi
  sleep 2
  SECONDS_WAITED=$((SECONDS_WAITED + 2))
done

echo "==> Training DFlash speculator"
CUDA_VISIBLE_DEVICES={q(recipe.train_gpus)} python scripts/train.py \\
  --verifier-name-or-path "$MODEL" \\
  --data-path "$OUTPUT_DIR" \\
  --vllm-endpoint "http://localhost:${{VLLM_PORT}}/v1" \\
  --hidden-states-path "$HIDDEN_STATES_DIR" \\
  --save-path {checkpoint_dir} \\
  --draft-vocab-size {recipe.draft_vocab_size} \\
  --epochs {recipe.epochs} \\
  --lr {recipe.learning_rate} \\
  --total-seq-len {recipe.seq_length} \\
  --speculator-type dflash \\
  --block-size {recipe.block_size} \\
  --max-anchors {recipe.max_anchors} \\
  --num-layers {recipe.num_layers} \\
  --target-layer-ids "${{TARGET_LAYER_IDS[@]}}" \\
  --on-missing generate \\
  --on-generate delete \\
  --save-best \\
  $TRUST_REMOTE_CODE_ARG

echo "Done. Best checkpoint should be under {checkpoint_dir}/checkpoint_best"
"""
